### ISSUE TITLE
Error with `ockam node list`

### ISSUE THREAD

**Issue by etorreborre** [build-trust/ockam#4193]
I followed the steps described in the [apply fine grained permissions walkthrough](https://docs.ockam.io/use-cases/apply-fine-grained-permissions-with-attribute-based-access-control-abac#step-by-step-walkthrough)
```
ockam enroll
ockam project information --output json > project.json
cp1_token=$(ockam project enroll --attribute component=control)
ockam node create control_plane1 --project project.json --enrollment-token $cp1_token
```
The node creation works fine but then executing `ockam node list` yields this error
```
Version 0.79.0, hash: 677f5196de552fb5d33c217cb835cd679ff2200a
`default tcp transport` not found
```
(using `OCKAM_LOG=trace` shows that this is an error code 70 if that helps)

**Comment by h20220145** [comment]
I'm experiencing a similar issue in ockam node start command , earlier it spawned a node , now it gives the output 

Version 0.79.0, hash: 
`node `default`` not found

**Comment by adrianbenavides** [comment]
This may have been solved after landing https://github.com/build-trust/ockam/pull/4194

I have run those steps on latest develop, running `ockam node list` after each step, and it returned the expected result each time.

**Comment by davide-baldo** [comment]
What's happening is that a command stall, `CTRL+C` is used and an embedded node state remains in `~/.ockam/nodes/`, being an embedded node no TCP transport is registered, and `ockam node list` always expect to find a TCP transport causing the failure.

One simple way to handle it is to skip every node without TCP registered or list/interact with them in a different way, but I'm wondering if we should avoid saving the embedded node state in the first place instead: if debugging is the reason the state is saved, maybe we can address it differently?

**Comment by hairyhum** [comment]
> This may have been solved after landing https://github.com/build-trust/ockam/pull/4194

Still happens for me after this was merged.

**Comment by etorreborre** [comment]
@adrianbenavides I am still getting this issue. I have the impression that this comes from anonymous nodes that are persisted in the `~/.ockam/nodes` directory.

**Comment by adrianbenavides** [comment]
@etorreborre do you know if it happened after merging https://github.com/build-trust/ockam/pull/4257? It was merged before your comment, but just to confirm.

**Comment by etorreborre** [comment]
@adrianbenavides I can't reproduce it anymore, so maybe I didn't have the latest version. Let's close!
